# Generated by Django 3.0 on 2022-07-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220711_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_voted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vote_count',
        ),
    ]
