# Generated by Django 3.0 on 2022-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220711_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
