# Generated by Django 3.0 on 2022-07-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
