# Generated by Django 3.0 on 2022-07-06 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evoting', '0002_auto_20220706_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatecategory',
            name='user',
        ),
        migrations.AddField(
            model_name='candidatecategory',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
