# Generated by Django 3.0 on 2022-07-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0003_auto_20220706_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecategory',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatecategory',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
