# Generated by Django 3.0 on 2022-07-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0004_auto_20220711_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatecategory',
            name='vote_count',
        ),
    ]
