# Generated by Django 3.0 on 2022-07-11 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evoting', '0006_candidatecategory_user_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatecategory',
            name='is_voted',
        ),
        migrations.RemoveField(
            model_name='candidatecategory',
            name='user_voted',
        ),
        migrations.AddField(
            model_name='candidatecategory',
            name='user_voted',
            field=models.ManyToManyField(null=True, related_name='user_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
