# Generated by Django 3.0 on 2022-07-14 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evoting', '0007_auto_20220711_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecategory',
            name='user_voted',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
